### ISSUE TITLE
Server error when using force_ssl true and running server with rackup

### ISSUE THREAD

**Issue by vlazar** [lotus/router#73]
```
$ lotus new force_ssl_test
```

```ruby
# config/routes.rb
get '/', to: ->(env) { [200, {}, ['OK']] }

# apps/web/application.rb
force_ssl true
```

```
$ bundle exec rackup
[2015-11-04 17:54:21] INFO  WEBrick 1.3.1
[2015-11-04 17:54:21] INFO  ruby 2.2.3 (2015-08-18) [x86_64-darwin15]
[2015-11-04 17:54:21] INFO  WEBrick::HTTPServer#start: pid=70829 port=9292
::1 - - [04/Nov/2015:17:54:31 +0300] "GET / HTTP/1.1" 301 - 0.0048
[2015-11-04 17:54:31] ERROR NoMethodError: undefined method `each' for "":String
	/Users/vlazar/.rvm/gems/ruby-2.2.3@force_ssl_test/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/Users/vlazar/.rvm/gems/ruby-2.2.3@force_ssl_test/gems/rack-1.6.4/lib/rack/lint.rb:708:in `each'
	/Users/vlazar/.rvm/gems/ruby-2.2.3@force_ssl_test/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/Users/vlazar/.rvm/gems/ruby-2.2.3@force_ssl_test/gems/rack-1.6.4/lib/rack/chunked.rb:23:in `each'
	/Users/vlazar/.rvm/gems/ruby-2.2.3@force_ssl_test/gems/rack-1.6.4/lib/rack/handler/webrick.rb:112:in `service'
	/Users/vlazar/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/vlazar/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/vlazar/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

```
$ http http://localhost:9292/
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/html; charset=ISO-8859-1
Date: Wed, 04 Nov 2015 14:04:16 GMT
Location: https://localhost:2300/
Server: WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18)
Transfer-Encoding: chunked


http: error: ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by vlazar** [comment]
For the reference.

I've traced this error by getting [H17 - Poorly formatted HTTP response](https://devcenter.heroku.com/articles/error-codes#h17-poorly-formatted-http-response) errors on Heroku in Lotus application started with ```bundle exec puma -C ./config/puma.rb```
